### ISSUE TITLE
Source not displaying for text.

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/BDRC-Lib-App#65]
I also noticed the source of the following one doesn't display under the title for work W1PD96682. The two entries at the bottom of the screenshot.

https://www.tbrc.org/?locale=bo#!rid=O1PD112371%7CO1PD1123714CZ87764%24W1PD96682

![k](https://user-images.githubusercontent.com/17675331/34196398-ef41d98e-e59c-11e7-8674-d31dedfbe50f.jpg)

**Comment by jeffwallman** [comment]
NT, I don't understand this issue.

**Comment by ngawangtrinley** [comment]
@jeffwallman the two titles at the bottom of the image are not works but outlines, and they should appear with the title of their parent just as the other titles above them. Here are the screens when I open them:

![k](https://user-images.githubusercontent.com/17675331/34215336-f71ac90c-e5df-11e7-9545-2e9388709eef.jpg)

![kl](https://user-images.githubusercontent.com/17675331/34215338-fca47cba-e5df-11e7-8f6c-6be051d97af1.jpg)

**Comment by subsystem7** [comment]
@ngawangtrinley I don't understand. Is this a data issue?

**Comment by eroux** [comment]
@ngawangtrinley can you test it again? is it still relevant?

**Comment by ngawangtrinley** [comment]
Well spotted! it's actually worse in this version! I believe it's not a data issue since none of the entries correct in the last version aren't displayed properly this time. 

![](https://user-images.githubusercontent.com/17675331/122242107-a249ff80-cef5-11eb-9e73-0fcdbdd39e0b.png)

**Comment by eroux** [comment]
Indeed, when searching on BUDA it looks like

https://library.bdrc.io/search?q=%22bkra%20shis%20chen%20po%27i%20mdo%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen&uilang=bo

the most relevant thing for this issue is the indication of the collection the text is in, like for the first result:

```
བཀྲ་ཤིས་ཆེན་པོའི་མདོ།

བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
```

the second line being the edition of the Canon where the text is. Continuing in that example, the text is `MW22084_0043` and the collection is `W22084`. The match that you'll get easily in the index is 

```json
"བཀྲ་ཤིས་ཆེན་པོའི་མདོ།":["MW26071_0044", "MW1PD96684_0759", "MW1PD96685_1026", "MW4CZ5369_0043", "MW22084_0043", "MW1PD127393_0317", "MW4CZ7445_0038", "MW1PD76588_76E5FD", "MW29468_0043", "MW3CN20612_0043"]
```

(in the latest version it's in `workparts-6.json`, it might be in another one in a future version). Two pieces of data are missing for you to fix this issue, continuing in this example:
- that `MW22084_0043` is in the collection `MW22084`
- that `MW22084` is named `བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽`

The first information you can infer by just taking the first part of the split of `MW22084_0043` on `_`. This is kind of a hack but it works. Then I don't think it would be reasonable at all to add `བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽` in `workparts-6.json` (it would make the indexes 10 times bigger at least), so it's probably best to take the labels in `works/84.json`:

```json
{"MW22084": {"pn": "དེལྷི་ཀརྨཔཨེ་ཆོདྷེཡ་གྱལྭཨེ་སུངྲབ་པརྟུན་ཁང་།", "pt": "x", "pd": "1976-1979", "title": ["བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽"],
```

so I think in terms of code this is easy, I don't know what kind of impact it might have on performance... wdyt @subsystem7 ?

**Comment by ngawangtrinley** [comment]
The old issue isn't the same as the current issue. The old issue is that some collection names weren't displayed, and the current one is that this feature disappeared all together.

The name of the collection used to appear under each entry. So you already have the code to get and display this information. It's just a question of getting it to work again.

**Comment by eroux** [comment]
well it used to work in the old version of the app, that's for sure. I can't say if it ever worked in the new one with the new format...

**Comment by subsystem7** [comment]
Assuming I understand this --> 

The new index design does not facilitate this data. We can discuss possible solutions to this, but the data no longer exists and the handling was factored out in this version starting from the beginning.  I can do an additional search for each result that merits it, but that is complicated and I believe would have serious performance implications. I could also figure out some method for pre-populating the data in the database, but frankly, I think we should add it back into the indices. It is the simplest solution, even though it will make the import larger. 

Any fix or hack will be easy, but time consuming.

**Comment by eroux** [comment]
ok, let me see how the data size changes if we put this in every entry of the `workpart-xxx.json` files. An alternative could be the following: since there are only ~2,000 possible values, what about a `rinames.json` that would just contain the names of these 2,000 entries, in a very basic way such as:

```json
{
  "MW22084": "བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽",
  "...": "..."
```

I think that shouldn't impact performance and also won't bloat the index. wdyt?

**Comment by subsystem7** [comment]
The rinames approach is similar to what we used to do to solve this very problem. It is a better solution. I’ll look at the old code and see how I did the caching in the past. It is possible that I can simply ready it into memory as a lookup when the app launches - or something like that.

**Comment by eroux** [comment]
I think that could work yes! I'm generating one right now so that we can test in real conditions

**Comment by subsystem7** [comment]
That sounds great, I will not have anything ready for 10 am

**Comment by eroux** [comment]
me neither, the file is generating and it takes a bit more time than I anticipated

**Comment by subsystem7** [comment]
inside of old Database,js 

```
processOutlineWorkTitleIndex(obj: {indexFile: IndexFile,indexFileContents: any}) {
		return new Promise((resolve, reject)=>{ 
			// this.shareStatus('Processing '+obj.indexFile.desc);
			localStorage.setItem('OutlineWorkIndex', JSON.stringify(obj.indexFileContents));
			this.outlineWorkIndex = obj.indexFileContents;
			resolve(obj.indexFile);
		});		
	}

```


inside of the old DatabaseResult.js 
```
_workTitleForOutline: string;
	
	workTitleForOutline(){
		if(this.isOutline) {
			if(!this._workTitleForOutline) {
				let dashIndex = this.nodeId.indexOf('-');
				if(dashIndex!=-1) {
					this._workTitleForOutline = this.db.outlineWorkIndex[this.nodeId.substring(0,dashIndex)];
				}
			}
			return this._workTitleForOutline;
		}
		return null;
	}
```

and in the database contructor:

```
			// revive the workIndex
			let _outlineWorkIndex = localStorage.getItem('OutlineWorkIndex');
			if(null!=_outlineWorkIndex) {
				try {
					this.outlineWorkIndex = JSON.parse(_outlineWorkIndex);
				} catch(e){
					console.log(e);
				}
			}

```
